### ISSUE TITLE
Mixing of char and byte indexing causes issues with Unicode

### ISSUE THREAD

**Issue by chris-laplante** [DevinR528/muncher#3]
Consider the example for `peek_until_count`:

```
use muncher::Muncher;

let input = "abcde";
let mut munch = Muncher::new(input);

let (start, end) = munch.peek_until_count(|ch| ch == &'d');
assert_eq!(&munch.text()[start..end], "abc");
assert_eq!(munch.eat(), Some('a'));
```

Internally, muncher mostly uses the chars() iterator of the input &str. The `start` and `end` as returned from `peek_until_count` correspond to the char indices. But slicing a string (`&munch.text()[start..end]`) is using byte indices. It all works fine for simple ASCII, but when you add some characters that take up multiple bytes, it falls apart:

```
use muncher::Muncher;

let input = "pánico en la discoteca";
let mut munch = Muncher::new(input);

let (start, end) = munch.peek_until_count(|ch| ch == &'d');
assert_eq!(&munch.text()[start..end], "pánico en la ");  // < this assert will fail
assert_eq!(munch.eat(), Some('a'));
```

The above code fails like this:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"pánico en la"`,
 right: `"pánico en la "`', src/muncher.rs:10:1
```

I am mostly done fixing the library to handle the codepoints correctly (see my branch https://github.com/chris-laplante/muncher/tree/codepoints).

What I'd like to do is fix the existing methods to always return the correct byte indices (and document them clearly as returning byte indices). I would also like to rename the method `peek_until_count` to something like `peek_until_range` to make it clearer.

Then I would propose adding flavors of methods that return char indices, e.g. `peek_until_range_chars`. What do you think?

**Comment by chris-laplante** [comment]
FYI this article was helpful to me as I was researching this past weekend: https://manishearth.github.io/blog/2017/01/14/stop-ascribing-meaning-to-unicode-code-points/

**Comment by DevinR528** [comment]
Yeah, this would be AWESOME! I feel like I've run into this problem a few times but I just used `Chars` and collecting to fix it which is not ideal, I also would just fix the method that broke so not actually fixing the whole problem. I looked over your branch quickly but from what I saw it makes sense (I just learned about this cool thing GitHub can do 
`https://github.com/DevinR528/muncher/compare/main...chris-laplante:codepoints`
(https://github.com/DevinR528/muncher/compare/main...chris-laplante:codepoints)
 you can compare branches, commits, timespans, etc).
